name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 14
        id: setup-java-14
        uses: actions/setup-java@v1
        with:
          java-version: "14.0.2"
          java-package: jdk
          architecture: x64

      - name: Build
        id: build
        run: ./gradlew build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/distributions
